baseURL = "https://my-blog-10e.pages.dev/"
languageCode = "ja"
title = "３人子育てドタバタ母さんの奮闘日記"
theme = "PaperMod"
defaultContentLanguage = "ja"
hasCJKLanguage = true


[params]
  author = "ドタバタ母さん"
  description = "3人の子供（小学１・４・６年生）を育てる、常にフル回転な母です！カオスすぎる我が家の日常を笑い飛ばしながら更新中。"
  homeInfoParams = {Title = "ようこそ！", Content = "白目をむきながらも、今日もなんとか生きてる！そんな全国のママ・パパと繋がれたら嬉しいです😊"}
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

[menu]
  [[menu.main]]
    name = "記事一覧"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "プロフィール"
    url = "/about/"
    weight = 20
[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
